### ISSUE TITLE
Shift to run

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#328]
In the tutorial it says hold down shift while moving to run but it doesn't work for me though pressing "." first does.

I think the same situation occurs for me with using control to disarm traps.

**Comment by NickMcConnell** [comment]
Shift+direction works fine for me.  The control+direction keymaps were removed.

**Comment by davidk64fnq** [comment]
Further testing and I found that shift plus arrow keys works while shift plus keypad doesn't. The use of control key to disarm traps is mentioned in the tutorial as an option.

**Comment by backwardsEric** [comment]
The text in the tutorial matches Sil 1.3's.  In both NarSil and Sil, control + a hjkl direction key will not work to disarm since most of those are used for other commands.  control + number not on the keypad does not work for me (macOS front end) though that seems to be the case both in Sil 1.3 and NarSil.  control + direction key will not work with the macOS front end since those key combinations are trapped by Cocoa and do not make it to the game.

**Comment by NickMcConnell** [comment]
I think I'm going to leave this as is - it is working for me as described in the tutorial on both Windows and Linux.
